# Generated by Django 6.0.2

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del negocio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
                'db_table': 'businesses',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('worker', 'Trabajador')], db_index=True, default='worker', max_length=20)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='posapp.business', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del producto en el servidor', primary_key=True, serialize=False, unique=True, verbose_name='ID del servidor')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('qr_code', models.CharField(blank=True, help_text='Código QR del producto (único por negocio)', max_length=100, null=True, verbose_name='Código QR')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/', verbose_name='Imagen')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio unitario del producto', max_digits=10, verbose_name='Precio')),
                ('stock', models.IntegerField(default=0, help_text='Cantidad disponible en inventario', verbose_name='Stock')),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Fecha y hora de última actualización', verbose_name='Actualizado en')),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Indica si el producto está activo (soft delete)', verbose_name='Activo')),
                ('business', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='posapp.business', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'products',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único de la venta', primary_key=True, serialize=False, verbose_name='UUID')),
                ('total', models.DecimalField(decimal_places=2, help_text='Total de la venta', max_digits=10, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación', verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de última actualización', verbose_name='Actualizado en')),
                ('synced_from_device', models.BooleanField(db_index=True, default=False, help_text='Indica si la venta fue creada en un dispositivo y sincronizada', verbose_name='Sincronizado desde dispositivo')),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Indica si la venta está activa (soft delete)', verbose_name='Activo')),
                ('business', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='posapp.business', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'sales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Cantidad de productos vendidos', verbose_name='Cantidad')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Precio total del item (quantity * product.price)', max_digits=10, verbose_name='Precio Total')),
                ('product', models.ForeignKey(help_text='Producto vendido', on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='posapp.product', verbose_name='Producto')),
                ('sale', models.ForeignKey(help_text='Venta a la que pertenece este item', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='posapp.sale', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Item de Venta',
                'verbose_name_plural': 'Items de Venta',
                'db_table': 'sale_items',
                'ordering': ['sale', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'updated_at'], name='products_business_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'qr_code'], name='products_business_qr_code_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active'], name='products_active_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['business', 'created_at'], name='sales_business_created_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['updated_at', 'active'], name='sales_updated_active_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['synced_from_device'], name='sales_synced_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['active'], name='sales_active_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale'], name='sale_items_sale_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['product'], name='sale_items_product_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('business', 'qr_code')},
        ),
        migrations.AlterUniqueTogether(
            name='saleitem',
            unique_together={('sale', 'product')},
        ),
    ]
