# Generated by Django 6.0.2 on 2026-02-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='products_busines_756c1b_idx',
            old_name='products_business_updated_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_busines_dcaf1b_idx',
            old_name='products_business_qr_code_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_active_20e15c_idx',
            old_name='products_active_idx',
        ),
        migrations.RenameIndex(
            model_name='sale',
            new_name='sales_busines_d6039d_idx',
            old_name='sales_business_created_idx',
        ),
        migrations.RenameIndex(
            model_name='sale',
            new_name='sales_updated_7ec777_idx',
            old_name='sales_updated_active_idx',
        ),
        migrations.RenameIndex(
            model_name='sale',
            new_name='sales_synced__85e036_idx',
            old_name='sales_synced_idx',
        ),
        migrations.RenameIndex(
            model_name='sale',
            new_name='sales_active_f4abd7_idx',
            old_name='sales_active_idx',
        ),
        migrations.RenameIndex(
            model_name='saleitem',
            new_name='sale_items_sale_id_caf625_idx',
            old_name='sale_items_sale_idx',
        ),
        migrations.RenameIndex(
            model_name='saleitem',
            new_name='sale_items_product_f7cd9c_idx',
            old_name='sale_items_product_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de última actualización', verbose_name='Actualizado en'),
        ),
    ]
