# Generated by Django 6.0.2 on 2026-02-21 21:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0003_sale_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['created_by'], name='sales_created_6c4eeb_idx'),
        ),
    ]
