# Generated by Django 6.0.2 on 2026-02-21 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0004_sale_pending_approval'),
        ('posapp', '0004_sale_sales_created_6c4eeb_idx'),
    ]

    operations = [
    ]
