# Generated by Django 6.0.2 on 2026-02-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0005_merge_20260221_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/None/', verbose_name='Imagen'),
        ),
    ]
