# Generated by Django 6.0.2 on 2026-02-25 07:51

import posapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=posapp.models.product_image_upload_to, verbose_name='Imagen'),
        ),
    ]
