# Generated by Django 6.0.2 on 2026-02-26 18:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('business', 'qr_code')},
        ),
        migrations.AddField(
            model_name='product',
            name='server_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del producto en el servidor', primary_key=True, serialize=False, unique=True, verbose_name='ID del servidor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('business', 'id'), ('business', 'qr_code')},
        ),
    ]
