# Generated by Django 6.0.2 on 2026-02-26 20:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0008_alter_product_unique_together_product_server_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='local_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('business', 'local_id'), ('business', 'qr_code')},
        ),
    ]
