# Generated by Django 6.0.2 on 2026-02-26 20:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0008_alter_product_unique_together_product_server_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('business', 'local_id'), ('business', 'qr_code')},
        ),
        migrations.AddField(
            model_name='product',
            name='local_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del producto en el servidor', primary_key=True, serialize=False, unique=True, verbose_name='ID del servidor'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='server_id',
        ),
    ]
