# Generated by Django 6.0.2 on 2026-03-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0011_saleitem_commission_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Precio total del item (cantidad * (precio - comisión))', max_digits=10, verbose_name='Precio Total'),
        ),
    ]
